#!/usr/bin/env bash
#coding: utf-8

export NODE_PATH="/usr/local/lib/node_modules"

glinkBase=INSTALLDIRglinkBase.js
basefile=./.glink/base

if [ -f "$basefile" ]; then 
	__glinkBase=`cat "$basefile"`
	if [ -f "$__glinkBase" ]; then 
		glinkBase=`cat "$__glinkBase"`
	else
		echo .glink/glinkBase contains wrong path
		exit 0
	fi
fi

nodejs "$glinkBase" $1 $2 $3 $4 $5 $6